build:
  image: golang:1.5
  commands:
    - make deps
    - make build
    - make test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-capistrano
    when:
      branch: master

plugin:
  name: Capistrano
  desc: Deploy software with Capistrano
  type: publish
  image: plugins/drone-capistrano
  labels:
    - ruby
    - capistrano
