sudo: required
services:
  - docker
language: go
go:
  - 1.5
install:
  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
before_script:
  - dockerfile="${VERSION}/Dockerfile"
  - dockertag="$VERSION"
  - true && [ "master" == "$TRAVIS_BRANCH" ] || dockertag="${TRAVIS_BRANCH}-${VERSION}"
script:
  - make deps
  - make build
  - make test
  - echo "* Building $DOCKER_IMAGE_NAME:$dockertag from $dockerfile"
  - docker build -t $DOCKER_IMAGE_NAME:$dockertag -f $dockerfile .
  - docker push $DOCKER_IMAGE_NAME:$dockertag
env:
  global:
    - DOCKER_IMAGE_NAME=Juicymo/drone-capistrano
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  matrix:
    - VERSION=2.4.2
    - VERSION=2.5.1