sudo: required
services:
  - docker
language: go
go:
  - 1.5
install:
  - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
script:
  - make deps
  - make build
  - make test
  - docker build -t $DOCKER_IMAGE_NAME .
  - if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG; fi && docker push $DOCKER_IMAGE_NAME
env:
  global:
    - secure: "Z96e1NSVgoZBFdW7aNvQUPVous4tZYL3L/2lDa9gYf1AMbZQlcjk6hSvpZRcKtEMA9g25RsodkauoTuHAjTH9ALTymN1JgYdKq/hRZO0mt65S9orr+nWBJn/azluv3bjs7nnJDg2FwGZ/o3QUJzHF5cC8vrXsgGXhIQczJSXe9jYNyjfq/paLL5mxUbS6AgdpF2XXu2RXlXCZP5pvMtK2F3JYP71pVvJam18A6mHljJxZZdNawEuovWH3pqOB/5ByyCUf7KgTeOLdGRn737eUO6vCwzQBSNAihMtI9ASKjlLJlNOahNkVFwH2GM4rGc1q++b2UsKXEFMxcePpWk32SIgNnAjyk59Vs0sB/s31DiHTVHOK4m/RXM8giEz/6p59JTpaKnCmCrGhZSCHRWOmrbaiRJt4MuLt2hRIvv9zAxnPeyNazd906w+qEPBNmwaaYYBUH6OxAmSrQfJS5y5MDiRWNBxaxJwx0H6u+7YMTsWY8GDbp6ziDW20LyqGdNITsltfwDjc2IZJ7+FCgi8E6Q5GBT7AKi2Rha6dYByHrPX6iYwDngMnXp9ASoN/VwDQ5bDqXs6VAM0LgyRfs+N/lIgpPIUc0Y4qXlEwVQ1Qa3RazB4ym54+YtXn/L37LiZWw5agp+EN1YR1iE9TKNje28SjepqSZRpbXIHq0/zRGs="
    - DOCKER_IMAGE_NAME=glaszig/drone-capistrano
